### ISSUE TITLE
Please adopt a specific open source LICENSE

### ISSUE THREAD

**Issue by penyuan** [mjskay/ggblend#4]
What a great package! Thanks for publishing it here.

However, right now the `LICENSE` file in this repository only lists the copyright year and authors, and is not a license. Please follow these [easy instructions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) in GitHub's documentation to choose and apply a proper open source license for this package, such as the GNU GPLv3. Otherwise, other people won't be allowed to study, share, and build on the code.

If it helps, I'm happy to submit a pull request with the needed changes.

**Comment by mjskay** [comment]
This is due to how CRAN requires MIT licenses to be configured for R packages --- the format of the LICENSE file is dictated by CRAN policies, and follows the pattern used by other well-known R packages (e.g. [ggplot2](https://github.com/tidyverse/ggplot2)). Without this format, packages will be rejected by CRAN.

The full license is in LICENSE.md.
